(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"CxSM",
  Authors -> {"Yang Ma"},
  Version -> "1.0",
  Date -> "02. 20. 22",
  Institutions -> {"University of Pittsburgh"},
  Emails -> {"mayangluon@pitt.edu"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}, {{MR$Null*QED, -MR$Null} -> Subscript[v, S], 0}};

FR$GoldstoneList={S[4], S[5]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "h1",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mh1,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "h2",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Mh2,
    Indices -> {} },

S[3] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HA",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHA,
    Indices -> {} },

S[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
Mh1[ ___ ] := Mh1;
Mh2[ ___ ] := Mh2;
MHA[ ___ ] := MHA;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[4] , S[4] , S[2] , S[2] ] == {{(-I/2)*(ca^2*delta2 + lamd*sa^2), 0}},

C[ S[5] , -S[5] , S[2] , S[2] ] == {{(-I/2)*(ca^2*delta2 + lamd*sa^2), 0}},

C[ S[1] , S[1] , S[2] , S[2] ] == {{(-I/2)*(ca^4*delta2 + ca^2*(3*d2 - 4*delta2 + 3*lamd)*sa^2 + delta2*sa^4), 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{((-3*I)/2)*(ca^4*d2 + 2*ca^2*delta2*sa^2 + lamd*sa^4), 0}},

C[ S[4] , S[4] , S[3] , S[3] ] == {{(-I/2)*delta2, 0}},

C[ S[5] , -S[5] , S[3] , S[3] ] == {{(-I/2)*delta2, 0}},

C[ S[1] , S[1] , S[3] , S[3] ] == {{(-I/2)*(ca^2*delta2 + d2*sa^2), 0}},

C[ S[2] , S[2] , S[3] , S[3] ] == {{(-I/2)*(ca^2*d2 + delta2*sa^2), 0}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{((-3*I)/2)*d2, 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{((-3*I)/2)*lamd, 0}},

C[ S[4] , S[4] , S[5] , -S[5] ] == {{(-I/2)*lamd, 0}},

C[ S[5] , S[5] , -S[5] , -S[5] ] == {{(-I)*lamd, 0}},

C[ S[4] , S[4] , S[1] , S[1] ] == {{(-I/2)*(ca^2*lamd + delta2*sa^2), 0}},

C[ S[5] , -S[5] , S[1] , S[1] ] == {{(-I/2)*(ca^2*lamd + delta2*sa^2), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-3*I)/2)*(ca^4*lamd + 2*ca^2*delta2*sa^2 + d2*sa^4), 0}},

C[ S[4] , S[4] , S[1] , S[2] ] == {{(-I/2)*ca*(delta2 - lamd)*sa, 0}},

C[ S[5] , -S[5] , S[1] , S[2] ] == {{(-I/2)*ca*(delta2 - lamd)*sa, 0}},

C[ S[1] , S[1] , S[1] , S[2] ] == {{((-3*I)/2)*ca*sa*(ca^2*(delta2 - lamd) + (d2 - delta2)*sa^2), 0}},

C[ S[1] , S[2] , S[2] , S[2] ] == {{((-3*I)/2)*ca*sa*(ca^2*(d2 - delta2) + (delta2 - lamd)*sa^2), 0}},

C[ S[1] , S[2] , S[3] , S[3] ] == {{(-I/2)*ca*(d2 - delta2)*sa, 0}},

C[ S[1] , S[2] , S[2] ] == {{(-I/2)*(ca^3*delta2*vev + ca*(-2*delta2 + 3*lamd)*sa^2*vev + ca^2*(3*d2 - 2*delta2)*sa*vs + delta2*sa^3*vs), 0}},

C[ S[1] , S[3] , S[3] ] == {{(-I/2)*(ca*delta2*vev + d2*sa*vs), 0}},

C[ S[4] , S[4] , S[1] ] == {{(-I/2)*(ca*lamd*vev + delta2*sa*vs), 0}},

C[ S[5] , -S[5] , S[1] ] == {{(-I/2)*(ca*lamd*vev + delta2*sa*vs), 0}},

C[ S[1] , S[1] , S[1] ] == {{((-3*I)/2)*(ca^3*lamd*vev + ca*delta2*sa^2*vev + ca^2*delta2*sa*vs + d2*sa^3*vs), 0}},

C[ S[1] , S[1] , S[2] ] == {{(-I/2)*(ca^2*(2*delta2 - 3*lamd)*sa*vev - delta2*sa^3*vev + ca^3*delta2*vs + ca*(3*d2 - 2*delta2)*sa^2*vs), 0}},

C[ S[2] , S[2] , S[2] ] == {{((-3*I)/2)*(-(ca^2*delta2*sa*vev) - lamd*sa^3*vev + ca^3*d2*vs + ca*delta2*sa^2*vs), 0}},

C[ S[2] , S[3] , S[3] ] == {{(I/2)*(delta2*sa*vev - ca*d2*vs), 0}},

C[ S[4] , S[4] , S[2] ] == {{(I/2)*(lamd*sa*vev - ca*delta2*vs), 0}},

C[ S[5] , -S[5] , S[2] ] == {{(I/2)*(lamd*sa*vev - ca*delta2*vs), 0}},

C[ S[5] , -S[5] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[5] , -S[5] , V[1] ] == {{(-I)*gc32, 0}, {I*gc32, 0}},

C[ -U[1] , U[32] , V[3] ] == {{I*gc33, 0}, {I*gc33, 0}, {0, 0}},

C[ -U[1] , U[31] , -V[3] ] == {{I*gc34, 0}, {I*gc34, 0}, {0, 0}},

C[ -S[5] , -U[32] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[32] , U[1] , -V[3] ] == {{I*gc36, 0}, {I*gc36, 0}, {0, 0}},

C[ S[4] , -U[32] , U[32] ] == {{-(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[32] , U[32] ] == {{((-I/4)*ca*EL^2*vev)/sw^2, 0}},

C[ S[2] , -U[32] , U[32] ] == {{((I/4)*EL^2*sa*vev)/sw^2, 0}},

C[ -U[32] , U[32] , V[1] ] == {{I*gc40, 0}, {I*gc40, 0}, {0, 0}},

C[ -U[32] , U[32] , V[2] ] == {{I*gc41, 0}, {I*gc41, 0}, {0, 0}},

C[ -S[5] , -U[32] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[32] , U[2] , -V[3] ] == {{I*gc43, 0}, {I*gc43, 0}, {0, 0}},

C[ S[5] , -U[31] , U[1] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ -U[31] , U[1] , V[3] ] == {{I*gc45, 0}, {I*gc45, 0}, {0, 0}},

C[ S[4] , -U[31] , U[31] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[31] , U[31] ] == {{((-I/4)*ca*EL^2*vev)/sw^2, 0}},

C[ S[2] , -U[31] , U[31] ] == {{((I/4)*EL^2*sa*vev)/sw^2, 0}},

C[ -U[31] , U[31] , V[1] ] == {{I*gc49, 0}, {I*gc49, 0}, {0, 0}},

C[ -U[31] , U[31] , V[2] ] == {{I*gc50, 0}, {I*gc50, 0}, {0, 0}},

C[ S[5] , -U[31] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[31] , U[2] , V[3] ] == {{I*gc52, 0}, {I*gc52, 0}, {0, 0}},

C[ S[5] , -U[2] , U[32] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[32] , V[3] ] == {{I*gc54, 0}, {I*gc54, 0}, {0, 0}},

C[ -S[5] , -U[2] , U[31] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[31] , -V[3] ] == {{I*gc56, 0}, {I*gc56, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/4)*ca*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[2] , -U[2] , U[2] ] == {{((I/4)*EL^2*sa*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[4, {e1x1}] , U[4, {e2x1}] , V[4, {e3x2}] ] == {{gc59*SUNF[e3x2, e1x1, e2x1], 0}, {gc59*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc60*SUNF[e1x2, e2x2, e3x2]), 0}, {gc60*SUNF[e1x2, e2x2, e3x2], 0}, {gc60*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc60*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc60*SUNF[e1x2, e2x2, e3x2]), 0}, {gc60*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc61*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc61*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc61*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[5] ] == {{I*gc62L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc62R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[4] ] == {{gc63L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc63R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc64L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc64R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{I*gc65L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc65R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[5] ] == {{I*gc66[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[4] ] == {{gc67L[e1x2, e2x2], 0}, {gc67R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc68L[e1x2, e2x2], 0}, {I*gc68R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{I*gc69L[e1x2, e2x2], 0}, {I*gc69R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[5] ] == {{I*gc70L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc70R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[4] ] == {{gc71L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc71R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc72L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc72R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{I*gc73L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc73R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ S[4] , -S[5] , V[1] , V[3] ] == {{-EL^2/(2*sw), 0}},

C[ -S[5] , S[1] , V[1] , V[3] ] == {{((I/2)*ca*EL^2)/sw, 0}},

C[ -S[5] , S[2] , V[1] , V[3] ] == {{((-I/2)*EL^2*sa)/sw, 0}},

C[ -S[5] , V[1] , V[3] ] == {{((I/2)*EL^2*vev)/sw, 0}},

C[ S[4] , -S[5] , V[3] ] == {{-gc78, 0}, {gc78, 0}},

C[ -S[5] , S[1] , V[3] ] == {{(-I)*gc79, 0}, {I*gc79, 0}},

C[ -S[5] , S[2] , V[3] ] == {{(-I)*gc80, 0}, {I*gc80, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc81, 0}, {I*gc81, 0}, {I*gc81, 0}, {(-I)*gc81, 0}, {(-I)*gc81, 0}, {I*gc81, 0}},

C[ S[4] , S[5] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[5] , S[1] , V[1] , -V[3] ] == {{((I/2)*ca*EL^2)/sw, 0}},

C[ S[5] , S[2] , V[1] , -V[3] ] == {{((-I/2)*EL^2*sa)/sw, 0}},

C[ S[5] , V[1] , -V[3] ] == {{((I/2)*EL^2*vev)/sw, 0}},

C[ S[4] , S[5] , -V[3] ] == {{-gc86, 0}, {gc86, 0}},

C[ S[5] , S[1] , -V[3] ] == {{(-I)*gc87, 0}, {I*gc87, 0}},

C[ S[5] , S[2] , -V[3] ] == {{(-I)*gc88, 0}, {I*gc88, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[5] , -S[5] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*ca^2*EL^2)/sw^2, 0}},

C[ S[1] , S[2] , V[3] , -V[3] ] == {{((-I/2)*ca*EL^2*sa)/sw^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2*sa^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*ca*EL^2*vev)/sw^2, 0}},

C[ S[2] , V[3] , -V[3] ] == {{((-I/2)*EL^2*sa*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc96, 0}, {(-I)*gc96, 0}, {(2*I)*gc96, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc97, 0}, {I*gc97, 0}, {I*gc97, 0}, {(-I)*gc97, 0}, {(-I)*gc97, 0}, {I*gc97, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc98, 0}, {(-I)*gc98, 0}, {(2*I)*gc98, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[5] ] == {{0, 0}, {I*gc99R[e1x2, e2x2], 0}},

C[ S[5] , -S[5] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[4] , S[1] , V[2] ] == {{-gc101, 0}, {gc101, 0}},

C[ S[4] , S[2] , V[2] ] == {{-gc102, 0}, {gc102, 0}},

C[ S[5] , -S[5] , V[2] ] == {{(-I)*gc103, 0}, {I*gc103, 0}},

C[ S[4] , -S[5] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[5] , S[1] , V[3] , V[2] ] == {{((-I/2)*ca*EL^2)/cw, 0}},

C[ -S[5] , S[2] , V[3] , V[2] ] == {{((I/2)*EL^2*sa)/cw, 0}},

C[ -S[5] , V[3] , V[2] ] == {{((-I/2)*EL^2*vev)/cw, 0}},

C[ S[4] , S[5] , -V[3] , V[2] ] == {{-EL^2/(2*cw), 0}},

C[ S[5] , S[1] , -V[3] , V[2] ] == {{((-I/2)*ca*EL^2)/cw, 0}},

C[ S[5] , S[2] , -V[3] , V[2] ] == {{((I/2)*EL^2*sa)/cw, 0}},

C[ S[5] , -V[3] , V[2] ] == {{((-I/2)*EL^2*vev)/cw, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc112, 0}, {I*gc112, 0}, {I*gc112, 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[5] , -S[5] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*ca^2*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[2] , V[2] , V[2] ] == {{((-I/2)*ca*EL^2*sa*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*sa^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*ca*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[2] , V[2] , V[2] ] == {{((-I/2)*EL^2*sa*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc120, 0}, {(-I)*gc120, 0}, {(2*I)*gc120, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc121*IndexDelta[e1x2, e2x2], 0}, {I*gc121*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc122*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc122*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc123*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc123*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc124*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc124*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc125*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc125*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc126[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc127[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc128*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc129*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc130L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc130R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc131L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc131R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc132*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc133L*IndexDelta[e1x2, e2x2], 0}, {I*gc133R*IndexDelta[e1x2, e2x2], 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc32 -> -EL,
     gc33 -> EL,
     gc34 -> -EL,
     gc36 -> EL,
     gc40 -> -EL,
     gc41 -> -((cw*EL)/sw),
     gc43 -> (cw*EL)/sw,
     gc45 -> -EL,
     gc49 -> EL,
     gc50 -> (cw*EL)/sw,
     gc52 -> -((cw*EL)/sw),
     gc54 -> (cw*EL)/sw,
     gc56 -> -((cw*EL)/sw),
     gc59 -> GS,
     gc60 -> -GS,
     gc61 -> -GS^2,
     gc62L[e1x2_, e2x2_] -> -IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc62R[e1x2_, e2x2_] -> IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc63L[e1x2_, e2x2_] -> -(Conjugate[yd[e2x2, e1x2]]/Sqrt[2]),
     gc63R[e1x2_, e2x2_] -> yd[e1x2, e2x2]/Sqrt[2],
     gc64L[e1x2_, e2x2_] -> -((ca*Conjugate[yd[e2x2, e1x2]])/Sqrt[2]),
     gc64R[e1x2_, e2x2_] -> -((ca*yd[e1x2, e2x2])/Sqrt[2]),
     gc65L[e1x2_, e2x2_] -> (sa*Conjugate[yd[e2x2, e1x2]])/Sqrt[2],
     gc65R[e1x2_, e2x2_] -> (sa*yd[e1x2, e2x2])/Sqrt[2],
     gc66[e1x2_, e2x2_] -> -Conjugate[yl[e2x2, e1x2]],
     gc67L[e1x2_, e2x2_] -> -(Conjugate[yl[e2x2, e1x2]]/Sqrt[2]),
     gc67R[e1x2_, e2x2_] -> yl[e1x2, e2x2]/Sqrt[2],
     gc68L[e1x2_, e2x2_] -> -((ca*Conjugate[yl[e2x2, e1x2]])/Sqrt[2]),
     gc68R[e1x2_, e2x2_] -> -((ca*yl[e1x2, e2x2])/Sqrt[2]),
     gc69L[e1x2_, e2x2_] -> (sa*Conjugate[yl[e2x2, e1x2]])/Sqrt[2],
     gc69R[e1x2_, e2x2_] -> (sa*yl[e1x2, e2x2])/Sqrt[2],
     gc70L[e1x2_, e2x2_] -> IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc70R[e1x2_, e2x2_] -> -IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc71L[e1x2_, e2x2_] -> Conjugate[yu[e2x2, e1x2]]/Sqrt[2],
     gc71R[e1x2_, e2x2_] -> -(yu[e1x2, e2x2]/Sqrt[2]),
     gc72L[e1x2_, e2x2_] -> -((ca*Conjugate[yu[e2x2, e1x2]])/Sqrt[2]),
     gc72R[e1x2_, e2x2_] -> -((ca*yu[e1x2, e2x2])/Sqrt[2]),
     gc73L[e1x2_, e2x2_] -> (sa*Conjugate[yu[e2x2, e1x2]])/Sqrt[2],
     gc73R[e1x2_, e2x2_] -> (sa*yu[e1x2, e2x2])/Sqrt[2],
     gc78 -> EL/(2*sw),
     gc79 -> (ca*EL)/(2*sw),
     gc80 -> -(EL*sa)/(2*sw),
     gc81 -> EL,
     gc86 -> EL/(2*sw),
     gc87 -> -(ca*EL)/(2*sw),
     gc88 -> (EL*sa)/(2*sw),
     gc96 -> -EL^2,
     gc97 -> (cw*EL)/sw,
     gc98 -> EL^2/sw^2,
     gc99R[e1x2_, e2x2_] -> -yl[e1x2, e2x2],
     gc101 -> -(ca*EL*(cw^2 + sw^2))/(2*cw*sw),
     gc102 -> (EL*sa*(cw^2 + sw^2))/(2*cw*sw),
     gc103 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc112 -> (cw*EL^2)/sw,
     gc120 -> -((cw^2*EL^2)/sw^2),
     gc121 -> -EL,
     gc122 -> (2*EL)/3,
     gc123 -> -EL/3,
     gc124 -> GS,
     gc125 -> GS,
     gc126[e1x2_, e2x2_] -> (EL*CKM[e1x2, e2x2])/(Sqrt[2]*sw),
     gc127[e1x2_, e2x2_] -> (EL*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*sw),
     gc128 -> EL/(Sqrt[2]*sw),
     gc129 -> EL/(Sqrt[2]*sw),
     gc130L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc130R -> (-2*EL*sw)/(3*cw),
     gc131L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc131R -> (EL*sw)/(3*cw),
     gc132 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc133L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc133R -> (EL*sw)/cw};

